version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gosec
    - loggercheck
    - makezero
    - musttag
    - noctx
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - gosec
          - noctx
          - wrapcheck
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
